apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: saga
spec:
  selector:
    app: payment-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: saga
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: keerthanalp/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGODB_URI
              value: "mongodb://mongo-service:27017"
            - name: MONGODB_DB
              value: "saga_db"
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: FAILURE_RATE
              value: "0.4"